### ISSUE TITLE
Comments get attached to the annotations group

### ISSUE THREAD

**Issue by herkulano** [thomas-lowry/status-annotations#1]
I had to remove this plugin because I realized that comments were being moved and sometimes even remove when the status was being updated. 

Also, when moving frames around I was losing the positioning of the comments because the comments were getting attached to the annotations group instead of the frame.

**Comment by thomas-lowry** [comment]
Can you go into more details?

The comments get attached to a particular frame. If you move the frames around when the plugin runs the annotations will get removed if the same frame does not exist anymore and they will Have their positions updated to the new x,y coordinates of the frame if it has moved to a new position. 

If you have a screen recording or screenshots it may help diagnose whether or not what you are experiencing is expected or a bug.

**Comment by herkulano** [comment]
Here's a screen recording of the problem:
https://www.loom.com/share/d95cc0effc554acabfc5f704ae931c2d

**Comment by thomas-lowry** [comment]
I think I can solve this by putting the group of annotations below all of the other frames. I will ship this update shortly.

**Comment by megaroeny** [comment]
@thomas-lowry actually the solution is to put the group at the TOP!! I was reporting this issue to Figma support, and they suggested moving the group of whatever is in the way of comments, to the top, and it worked!!

**Comment by thomas-lowry** [comment]
Hey @herkulano @megaroeny thank you for the suggestions. I updated the plugin this evening so the annotations sit at the top of all frames so that they don't interfere with comments.

**Comment by megaroeny** [comment]
> Hey @herkulano @megaroeny thank you for the suggestions. I updated the plugin this evening so the annotations sit at the top of all frames so that they don't interfere with comments.

Just realized that the plugin still puts the generated group at the bottom of the layers list, but if you use the Refresh command, it moves it to the top. Would you be able to have the group generated at the top of the layers list as well? Thanks!

**Comment by megaroeny** [comment]
@thomas-lowry I _think_ Figma finally fixed the bug that groups at the bottom of the layer list, were overlapping other objects when trying to comment?! Would you be able to confirm this? If so, I think you can revert these changes and have the `status_annotations` group stay at the bottom now!
