### ISSUE TITLE
Placement & Inner-shadow stopped working

### ISSUE THREAD

**Issue by megaroeny** [thomas-lowry/status-annotations#5]
I suddenly noticed that the Status Annotations plugin was behaving weirdly. Two things:

1. Doesn't place the annotation in the correct spot
2. Stopped adding the colored inner shadow on the bottom of them

I'm also using Figma Beta, wonder if that has anything to do witih it.

**Comment by megaroeny** [comment]
Just confirmed that Beta is not a factor. Did this in the production version of the desktop app too.

**Comment by thomas-lowry** [comment]
Fixed! Issue introduced by small bug in drop shadow spread release that is resolved. Thanks @megaroeny!
