### ISSUE TITLE
Doesn't work on Variant set

### ISSUE THREAD

**Issue by megaroeny** [thomas-lowry/status-annotations#6]
I'm trying to run the plugin on a variant component set, but it doesn't let me.

**Comment by thomas-lowry** [comment]
Hey @megaroeny, I added support for this in the update I pushed this evening!

**Comment by megaroeny** [comment]
> Hey @megaroeny, I added support for this in the update I pushed this evening!

You da man! Thank you! I'm sure others will appreciate it. 😊
